### ISSUE TITLE
Garbage Collection problems.

### ISSUE THREAD

**Issue by elijahlrc** [daverau/leafy#2]
I'm quickly looking over code and making notes, none of what I say is probably useful/coherent.
Could set text less often, under the hood that could be allocating new strings every frame. (Line 89 in game.js). Strings are immutable in most languages, probably JS too, so whenever you change them that's a new allocation. So back of napkin calculation, changing 200 characters each frame is 200chars_60fps_2bytes is = 24kb of allocations per second from just the UI strings. Doesn't seem like it would kill performance, but might as well update those strings only when they actually change. 
I gotta get to work, but I didn't find anything else with a quick look. Good luck!

**Comment by daverau** [comment]
Hah, thanks for the issue @elijahlrc! Turns out it was the text setting all along! Performance is great now that I put that update on a timer every 30 frames.
